import Head from 'next/head'
import Image from 'next/image'
import AddPost from '../components/posts/AddPost'
import Feed from '../components/Feed'
import FiltersBar from '../components/posts/FiltersBar'
import { getPosts } from '../data'

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>FakeOrFact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddPost />
      <FiltersBar />
      <Feed posts={posts} />
    </>
  )
}

export const getServerSideProps = async (ctx) => {
  try {
    const cookies = nookies.get(ctx)
    const token = await firebaseAdmin.auth().verifyIdToken(cookies.token)

    // the user is authenticated!
    const { uid, email } = token

    // FETCH STUFF HERE!! 🚀
    const posts = await getPosts()

    return {
      props: {
        message: `Your email is ${email} and your UID is ${uid}.`,
        posts,
      },
    }
  } catch (err) {
    // ctx.res.writeHead(302, { Location: '/' })
    // ctx.res.end()
    // FETCH STUFF HERE!! 🚀
    const posts = await getPosts()
    return { props: posts }
  }
}
