import Head from 'next/head'
import Image from 'next/image'
import AddPost from '../components/posts/AddPost'
import Feed from '../components/Feed'
import FiltersBar from '../components/posts/FiltersBar'
import { getPosts } from '../data'

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>FakeOrFact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddPost />
      <FiltersBar />
      <Feed posts={posts} />
    </>
  )
}

export async function getServerSideProps(context) {
  const posts = await getPosts()
  return {
    props: posts,
  }
}
